version: "3.9"

services:
  api:
    build: /parec-backend/.
    container_name: backend
    ports:
      - 8080:8000
    networks:
      - backend_net

  web:
    build: /parec-frontend/.
    container_name: frontend
    ports:
      - 81:4173
    networks:
      - backend_net
    depends_on:
      - api   #frontend only workes if backend already deployed

networks:
  backend_net:
    
 
  