version: "3.9"

services:
  es:
    image: elasticsearch:8.6.1
    container_name: es
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - es_net

  backend:
    build: ./parec-backend/.
    container_name: backend
    networks:
      - backend_net
      - es_net
    depends_on:
      - es
    environment:
      - ELASTICSEARCH_URL=http://es:9200/

  frontend:
    build: ./parec-frontend/.
    container_name: frontend
    ports:
      - 80:80
    networks:
      - backend_net
    depends_on:
      - backend   #frontend only works if backend already deployed

networks:
  backend_net:
  es_net: 

volumes:
  esdata:
    driver: local