version: "3.9"

services:
  backend:
    build: /parec-backend/.
    container_name: backend
    networks:
      - backend_net

  frontend:
    build: /parec-frontend/.
    container_name: frontend
    ports:
      - 80:80
    networks:
      - backend_net
    depends_on:
      - backend   #frontend only works if backend already deployed

networks:
  backend_net:
    
 
  